experiment:
  generate_experiment_dir: /mnt/data/experiments/nils/new_classification_seeded_runs
  experiment_name: 1.00x_train # prefix
  experiment_type: seeded_runs # standard, seeded_runs, sweew
  partition_name: 1.00x_train
  benchmark_dir: /mnt/data/cc_benchmark/classification_v0.7
  best_hparam_config: /mnt/data/experiments/nils/new_classification_results/seeded_runs.json
  num_seeds: 2
model:
  model_generator_module_name: ccb.torch_toolbox.model_generators.timm_generator
  backbone: convnext_base
wandb:
  project: ccb # wandb project name
  entity: climate-benchmark # user or team entity that hosts a project