encoder_type: resnet18  # resnet18, convnext_base
decoder_type: Unet
encoder_weights: imagenet
image_size: 224 # desired image input dimension to model
pretrained: True
lr_backbone: 1.0e-6
lr_head: 1.0e-4
optimizer: sgd
head_type: linear
hidden_size: 512
loss_type: crossentropy
batch_size: 2