backbone: convnext_base  # resnet18, convnext_base, vit_tiny_patch16_224, vit_small_patch16_224. swinv2_tiny_window16_256
pretrained: True
image_size: 256 # desired image input dimension to model
lr_backbone: 1.0e-6
lr_head: 1.0e-4
optimizer: sgd
hidden_size: 512
head_type: linear # classification
loss_type: crossentropy
batch_size: 2