---
pipeline:

  build-docker:
    when:
      event:
        - push
    environment:
      - IMAGE_NAME=registry.console.elementai.com/snow.rg_climate_benchmark/base
      - VOLATILE_IMAGE_NAME=volatile-images.borgy.elementai.net/snow.rg_climate_benchmark
      - DEPENDENCY_FILES=Dockerfile requirements.txt
    commands:
      - docker login -u console -p "$EAI_TOKEN" https://registry.console.elementai.com
      # Check if we need to rebuild the docker image
      - docker pull $IMAGE_NAME:${DRONE_BRANCH} || echo "Image $IMAGE_NAME:${DRONE_BRANCH} not in image repository."
      - export DEPENDENCY_TAG=$(cat $DEPENDENCY_FILES | md5sum | cut -d' ' -f1)
      - export CUR_DEPENDENCY_TAG=$(docker inspect --format='{{index .Config.Labels "DEPENDENCY_TAG"}}' $IMAGE_NAME:${DRONE_BRANCH}) || echo "Skip."
      - echo "Dependency hash $CUR_DEPENDENCY_TAG (repository) vs $DEPENDENCY_TAG (current)"
      - >
        if [ "$CUR_DEPENDENCY_TAG" != "$DEPENDENCY_TAG" ] ; then
          echo "Need to rebuilt the image since dependency files have changed."
          docker build . --label DEPENDENCY_TAG="$DEPENDENCY_TAG" -t "$IMAGE_NAME:${DRONE_BRANCH}";
          docker push "$IMAGE_NAME:${DRONE_BRANCH}";
        else
          echo "No need to rebuild image. Dependency files have not changed"
        fi
      # Push to local volatile image repo for other tasks that need to run in the image
      - docker tag "$IMAGE_NAME:${DRONE_BRANCH}" "$VOLATILE_IMAGE_NAME:${DRONE_BRANCH}"
      - docker push "$VOLATILE_IMAGE_NAME:${DRONE_BRANCH}"
    image: images.borgy.elementai.net/eai/build
    secrets: [ eai_token ]

  
  tests:
    when:
      event:
        - push
    environment:
      - BORGY_RAM=16
      - BORGY_CPU=2
      - BORGY_GPU=1
    commands:
      - pip install --upgrade pip && pip install pytest
      - pytest
    image: volatile-images.borgy.elementai.net/snow.rg_climate_benchmark:${DRONE_BRANCH}


  flake8:
    when:
      event:
        - push
    environment:
      - BORGY_RAM=16
      - BORGY_CPU=2
    commands:
      - pip install --upgrade pip && pip install flake8
      - export PATH=$PATH:"/home/_drone/.local/bin"
      - flake8 .
    image: volatile-images.borgy.elementai.net/snow.rg_climate_benchmark:${DRONE_BRANCH}
