repos:
    -   repo: https://github.com/psf/black
        rev: 22.3.0
        hooks:
        -   id: black
            args: [--skip-magic-trailing-comma]

    -   repo: https://gitlab.com/pycqa/flake8.git
        rev: 3.9.2
        hooks:
        -   id: flake8
  
