[tool.poetry]
name = "climate-change-benchmark"
version = "0.0.1"
description = ""
authors = ["ATG Vision <atg-vision@servicenow.com>"]
packages = [
    { include = "ccb" }
]

[tool.poetry.dependencies]
python = ">=3.8.0,<4"
wandb = ">=0.10.26"
earthengine-api = "0.1.269"
clip = { git = "https://github.com/openai/CLIP.git", rev = "8cad3a736a833bc4c9b4dd34ef12b52ec0e68856" }
regex = "2021.8.3"
ftfy = "6.0.3"
lightning-bolts = "0.3.4"
lmdb = "1.2.1"
onnx = "1.9.0"
onnx2pytorch= "0.3.0"
pandas = "1.3.1"
pyshp = "2.1.3"
pytorch-lightning = "1.6.0"
pytorch-lightning-bolts = "0.3.2"
rasterio = "1.2.4"
scikit-image = "0.18.1"
scikit-learn = "0.24.2"
Shapely = "1.7.1"
torchvision = "0.11.3"
torchmetrics = "0.8.2"
torchgeo = "0.2.0"
torch = "1.10.2"
h5py = "3.3.0"
xmltodict = "0.12.0"
"ruamel.yaml" = "0.17.21"
deepspeed = "0.6.5"
segmentation-models-pytorch = { git = "https://github.com/ElementAI/segmentation_models.pytorch.git", rev = "903115cb156e7bd6d28148e7db66584b3b81b4a8" }
timm = { git = "https://github.com/rwightman/pytorch-image-models.git", branch = "master"}

[tool.poetry.dev-dependencies]
black = "*"
pytest = "*"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.poetry.scripts]
ccb-expgen = "ccb.experiment.experiment_generator:start"
ccb-trainer = "ccb.torch_toolbox.trainer:start"
ccb-sweep-trainer = "ccb.torch_toolbox.sweep_trainer:start"
ccb-toolkit = "toolkit.dispatch_toolkit:start"
