[tool.poetry]
name = "climate-change-benchmark"
version = "0.0.1"
description = ""
authors = ["ATG Vision <atg-vision@servicenow.com>"]
packages = [
    { include = "ccb" }
]

[tool.poetry.dependencies]
python = ">=3.8.0,<4"
wandb = ">=0.10.26"
earthengine-api = "0.1.269"
clip = { git = "https://github.com/openai/CLIP.git", rev = "8cad3a736a833bc4c9b4dd34ef12b52ec0e68856" }
regex = "2021.8.3"
ftfy = "6.0.3"
lightning-bolts = "0.3.4"
lmdb = "1.2.1"
pandas = "1.3.1"
pyshp = "2.1.3"
pytorch-lightning = "1.6.0"
pytorch-lightning-bolts = "0.3.2"
rasterio = "1.2.4"
scikit-image = "0.18.1"
scikit-learn = "0.24.2"
Shapely = "1.7.1"
torchvision = "0.13.0"
torchmetrics = "0.8.2"
torchgeo = "0.2.0"
torch = "1.12.0"
h5py = "3.3.0"
xmltodict = "0.12.0"
"ruamel.yaml" = "0.17.21"
segmentation-models-pytorch = { git = "https://github.com/ElementAI/segmentation_models.pytorch.git", rev = "903115cb156e7bd6d28148e7db66584b3b81b4a8" }
timm = { git = "https://github.com/rwightman/pytorch-image-models.git", branch = "master"}
mypy = ">=0.900"
setuptools = "59.5.0"
types-PyYAML = "6.0.10"
ipykernel = "6.15.2"
ipyplot = "^1.1.1"
ipyleaflet = "^0.17.1"
seaborn = "^0.12.0"
albumentations = ">=1.2.1"

[tool.poetry.dev-dependencies]
black = "22.3.0"
pytest = "7.1.2"
pytest-cov = "3.0.0"
isort = "5.10.1"
colorama = "0.4.4"
flake8 = "4.0.1"
pydocstyle = "6.1.1"

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
line_length = 120

[tool.flake8]
max-line-length = 120
max-complexity = 23

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
exclude = "(docs|data)/"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
filterwarnings = [
  "ignore::PossibleUserWarning",
]

[tool.poetry.scripts]
ccb-expgen = "ccb.experiment.experiment_generator:start"
ccb-trainer = "ccb.torch_toolbox.trainer:start"
ccb-sweep-trainer = "ccb.torch_toolbox.sweep_trainer:start"
ccb-toolkit = "toolkit.dispatch_toolkit:start"
