name: tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  pytest:
    name: pytest
    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: Agg
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install apt dependencies (Linux)
      run: sudo apt-get install unrar
      if: ${{ runner.os == 'Linux' }}
    - name: Install Dependencies with poetry
      uses: Gr1N/setup-poetry@v7
      run: |
        poetry lock --no-update
        poetry install
        poetry show
    - name: Run pytest checks
      run: |
        pytest -m --cov=ccb --cov-report=xml
    - name: Report coverage
      uses: codecov/codecov-action@v2
