name: tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  pytest:
    name: pytest
    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: Agg
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install apt dependencies (Linux)
      run: sudo apt-get install unrar
      if: ${{ runner.os == 'Linux' }}
    - name: Install brew dependencies (macOS)
      run: brew install rar
      if: ${{ runner.os == 'macOS' }}
    - name: Install Dependencies
      run: |
        pip install poetry
        poetry install
        poetry show
    - name: Run pytest checks
      run: pytest --cov=torchgeo --cov-report=xml
    - name: Report coverage
      uses: codecov/codecov-action@v2
